### PR TITLE
Fix typo in error message

### PR DESCRIPTION
**Pull request by ralienpp**
When attempting to use signClient with `-clientside` I get an error message that contains a typo.

### CODE REVIEW

**Comment by ralienpp** [comment]
After the recent developments, I would consider rewriting that as `"Client-side construction is only supported in the enterprise version"`, such that the error message gives a clue about what to do next.

**Comment by netmackan** [comment]
Thank you for the PR. I think we should accept your first suggestion or some alternative of the second one.

To be precise: if you get this error message it is because there exists no FileSpecificHandlerFactory on the classpath that supports client-side construction. 

It is true that by default in Community Edition there is (currently) no such implementation while in Enterprise Edition one exists. However, it is possible to extend SignServer and add an implementation for this which then will be available at runtime. Therefore, it wouldn't be complete correct to say that just because there is no implementation available that one needs to use the enterprise edition.

Need to think about this some more, either go with first suggestion of just fixing the spelling or maybe add some hint similar to second comment:
```No client-side construction implementation available. Maybe you need to use enterprise edition of SignClient```

**Comment by ralienpp** [comment]
If one could count on URL immutability in the documentation, perhaps this would work?

`No client-side construction implementation available, does your version support it?\nSee https://doc.primekey.com/x/ewFu#ClientSideHashing-OpenPGPSigning`

**Comment by netmackan** [comment]
I like your suggestion with the URL but we should drop the last part that goes to the OpenPGP-specific section as this is generally about all file-types. So URL should be https://doc.primekey.com/x/ewFu .
Can you update the PR?

**Comment by ralienpp** [comment]
Hi, I updated it.

**Comment by oscarnorman1** [comment]
Hello and thank you for your contribution, @ralienpp! We have now processed your pull request, and everything looks okay. Your changes will be merged in an upcoming release.

If you want to be part of our contributors' list on our org page (https://www.signserver.org/contributors/), please let us know with what credentials you want to be presented with.

**Pull request merged**
